name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        ###### Repository/Build Configurations ######
        app_location: "/" # App source code path relative to repository root
        app_build_command: "yarn docs:build"
        output_location: "docs/.vitepress/dist" # Built app content directory, relative to app_location - optional
        ###### End of Repository/Build Configurations ######

    - name: Build
      run: |
        yarn
        yarn run docs:build
